# Generated by Django 5.1.4 on 2025-04-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='course_icons/'),
        ),
    ]
