# Generated by Django 5.1.4 on 2025-04-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='enrolled_users', to='myapp.lesson'),
        ),
    ]
