# Generated by Django 5.1.4 on 2025-04-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_userprofile_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='courses',
            field=models.ManyToManyField(related_name='user_profiles', to='myapp.lesson'),
        ),
    ]
