# Generated by Django 5.1.4 on 2025-05-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_dailyquest_userdailyquest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hearts',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_heart_refill',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
