# Generated by Django 5.1.4 on 2025-05-22 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_userprofile_hearts_userprofile_last_heart_refill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_heart_refill',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 22, 5, 57, 33, 533916, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
