# Generated by Django 5.1.4 on 2025-05-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_userprofile_last_heart_refill'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_xp',
            field=models.IntegerField(default=0),
        ),
    ]
