# Generated by Django 5.1.4 on 2025-05-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_userprofile_total_xp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='xp',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hearts',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_heart_refill',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
