# Generated by Django 5.1.4 on 2025-05-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_created_at_notification_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
